# Generated by Django 3.2.4 on 2021-06-24 21:17

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210624_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=backend.models.generate_imageset_upload_to),
        ),
    ]
